name: Build Geode Mod

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Android64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Android64

      - name: Create geode package
        run: |
          mkdir -p output
          geode package new \
            --binary build/libart-sprite-import.so \
            --output output/dexname.art-sprite-import.geode \
            .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexname.art-sprite-import
          path: output/dexname.art-sprite-import.geode
          if-no-files-found: error
