name: Build Geode Mod

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Android64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          combine: true
          target: Android64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexname.art-sprite-import
          path: ${{ steps.build.outputs.build-output }}
